server:
  port: 8080

spring:
  # 데이터베이스 연결 설정 (HikariCP 사용)
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE          # Oracle DB의 JDBC URL (최상위에 위치)
    username: mirero                                  # 데이터베이스 사용자 이름
    password: mirero                                  # 데이터베이스 비밀번호
    driver-class-name: oracle.jdbc.OracleDriver       # Oracle JDBC 드라이버 클래스 이름

    hikari:
      pool-name: Hikari Connection Pool               # 커넥션 풀 이름
      maximum-pool-size: 10                           # 최대 커넥션 풀 크기
      minimum-idle: 5                                 # 최소 유지할 커넥션 수
      connection-timeout: 30000                       # 커넥션 타임아웃 (밀리초)
      idle-timeout: 600000                            # 커넥션 풀에서의 유휴 시간 (밀리초)
      max-lifetime: 1800000                           # 커넥션 최대 생존 시간 (밀리초)
      connection-init-sql: SELECT 1 FROM DUAL         # 커넥션 초기화 쿼리 (Oracle 테스트 쿼리)

  # 트랜잭션 설정 (옵션)
  transaction:
    rollback-on-commit-failure: true                 # 트랜잭션 커밋 실패 시 롤백 설정

mybatis:
  # MyBatis 매퍼 파일 위치 설정
  mapper-locations: classpath:mapper/**/*.xml           # MyBatis 매퍼 파일 위치 (src/main/resources/mapper의 모든 하위폴더의 .xml 파일

  # 설정 옵션
  configuration:
    map-underscore-to-camel-case: true               # DB 필드명을 카멜 케이스 자바 필드명으로 자동 매핑 (예: user_name -> userName)
    cache-enabled: false                             # 2차 캐시 사용 여부 (로컬 환경에서는 보통 비활성화)
    default-fetch-size: 100                          # 기본 페치 크기 설정
    default-statement-timeout: 30                    # 기본 쿼리 타임아웃 시간(초) 설정
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 콘솔에 MyBatis SQL 로그 출력
