-- MEMBER 테이블 정의
CREATE TABLE MEMBER (
    ID RAW(16) DEFAULT SYS_GUID() NOT NULL,                -- 회원 ID (Primary Key)
    EMAIL VARCHAR2(100) NOT NULL,       -- 회원 이메일
    NAME VARCHAR2(50) NOT NULL,         -- 회원 이름
    PASSWORD VARCHAR2(255) NOT NULL,    -- 비밀번호
    ENABLED NUMBER(1,0) NOT NULL,       -- 계정 활성화 상태 (0: 비활성화, 1: 활성화)
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID),
    CONSTRAINT CHK_MEMBER_ENABLED CHECK (ENABLED IN (0, 1))  -- 활성화 상태 제한 조건
);

COMMENT ON COLUMN MEMBER.ENABLED IS '계정 활성화 상태';
COMMENT ON COLUMN MEMBER.ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';

-- ROLE 테이블 정의
CREATE TABLE ROLE (
    ID RAW(16) NOT NULL,                -- 권한 ID (Primary Key)
    NAME NUMBER(3,0) NOT NULL,          -- 권한 이름 (예: 0, 1, 2 등)
    CONSTRAINT PK_ROLE PRIMARY KEY (ID),
    CONSTRAINT CHK_ROLE_NAME CHECK (NAME BETWEEN 0 AND 2)  -- 권한 이름 제한 조건
);

COMMENT ON COLUMN ROLE.NAME IS '권한 이름';
COMMENT ON COLUMN ROLE.ID IS '권한 아이디';

-- MEMBER_ROLE_MAPPING 테이블 정의
CREATE TABLE MEMBER_ROLE_MAPPING (
    ID RAW(16) NOT NULL,                -- 매핑 ID (Primary Key)
    MEMBER_ID RAW(16),                  -- 회원 ID (Foreign Key)
    ROLE_ID RAW(16),                    -- 권한 ID (Foreign Key)
    CONSTRAINT PK_MEMBER_ROLE_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_MEMBER_ROLE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE
);

COMMENT ON COLUMN MEMBER_ROLE_MAPPING.ID IS '회원 권한 매핑 아이디';
COMMENT ON COLUMN MEMBER_ROLE_MAPPING.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN MEMBER_ROLE_MAPPING.ROLE_ID IS '권한 ID';